name: TaskFlow Single Server CI/CD

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Test backend
        run: |
          cd backend
          pip install -r requirements.txt
          python manage.py test

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Test frontend
        run: |
          cd frontend
          npm ci
          npm run test
          npm run build

  deploy-staging:
    runs-on: self-hosted
    needs: test
    if: github.ref == 'refs/heads/develop'
    environment: staging
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to staging
        run: |
          cd /opt/taskflow/staging
          git pull origin develop
          docker-compose down
          docker-compose build
          docker-compose up -d
          sleep 30
          curl -f http://localhost/health

  deploy-production:
    runs-on: self-hosted
    needs: test
    if: github.ref == 'refs/heads/main'
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to production
        run: |
          cd /opt/taskflow/production
          git pull origin main
          
          # Blue-green deployment simulation
          docker-compose -f docker-compose.yml -f docker-compose.backup.yml up -d --no-deps backend frontend
          sleep 30
          
          # Health check
          if curl -f https://taskflow.local/health; then
            echo "Deployment successful"
            docker-compose down --remove-orphans
            docker-compose up -d
          else
            echo "Health check failed, rolling back"
            docker-compose -f docker-compose.backup.yml up -d
            exit 1
          fi

  backup:
    runs-on: self-hosted
    if: github.ref == 'refs/heads/main'
    schedule:
      - cron: '0 2 * * *'  # Daily at 2 AM
    steps:
      - name: Backup databases
        run: |
          /opt/taskflow/scripts/backup-all.sh